language: nix

before_install:
  nix-env --install --attr nixpkgs.haskellPackages.hlint

script:
  hlint src example
  nix-build

notifications:
  slack: freizl:D42Dy68Q4Cj8Bjw5Qi9mZrQf


# http://docs.haskellstack.org/en/stable/travis_ci.html

# language: haskell
# 
# branches:
#   only:
#     - master
# 
# sudo: false
# 
# env:
#   matrix:
#     - TEST_SUITE=lint
#     - TEST_SUITE=build
#     - TEST_SUITE=nightly
# 
# cache:
#   directories:
#     - $HOME/.stack/
# 
# before_install:
#   - mkdir -p ~/.local/bin
#   - export PATH=~/.local/bin:$PATH
#   - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
#   - chmod a+x ~/.local/bin/stack
#   - git --version
#   - stack --version
# 
# install:
#   - stack +RTS -N2 -RTS setup --no-terminal --skip-ghc-check
# 
# script:
#   - make ci-$TEST_SUITE
# 
